name = "quran-api-proxy"
main = "worker-kv-enhanced.js"
compatibility_date = "2024-01-01"

# Environment variables for production
[env.production.vars]
ALLOWED_ORIGINS = "https://quran.zikirnurani.com,https://quranwbw.com,https://localhost:5173"
CACHE_TTL = "3600"
RATE_LIMIT_REQUESTS = "1000"

# KV namespace for Quran data storage
[[env.production.kv_namespaces]]
binding = "KV_QURAN_DATA"
id = "ad6b351d06e140179e5c6ea8c4e81239"
preview_id = "c7d00e61f094403fb99e7a889bce967c"

# Custom domains (optional)
[[env.production.routes]]
pattern = "digitalquranaudio.zikirnurani.com/*"
zone_name = "zikirnurani.com"
